name = "soberana-server"
author = "roridev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afff92fdd59b6ed44df85fe674e42ead9d948a1b201d6131932b685488dcb546"

[versions]
minecraft = "1.19.2"
quilt = "0.17.5-beta.3"

[options]
acceptable-game-versions = ["1.19.1"]
