name = "soberana-server"
author = "roridev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55215bf748b539b43696676c7cf13d597e9815e1175443ca8debce917a11f719"

[versions]
minecraft = "1.19.2"
quilt = "0.17.5-beta.3"

[options]
acceptable-game-versions = ["1.19.1"]
