name = "soberana-server"
author = "roridev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fec1066b589ee16ed6a7e4195deaf8212a3b5625c6f46f09c9ffb54421bc0bb3"

[versions]
minecraft = "1.19.2"
quilt = "0.17.5-beta.3"

[options]
acceptable-game-versions = ["1.19.1"]
