name = "soberana-server"
author = "roridev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2851f1db1946588329fb280b445fe93a4383acd3af8ef7eb295b7e5b0375fa0b"

[versions]
minecraft = "1.19.2"
quilt = "0.17.5-beta.3"
